version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: smart-classroom-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: smart-classroom
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - smart-classroom-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: smart-classroom-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-classroom-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-classroom-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/smart-classroom?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-here
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - smart-classroom-network

  # AI Service
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: smart-classroom-ai-service
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
      PORT: 5001
      HUGGINGFACE_API_KEY: your-huggingface-api-key
      VOSK_MODEL_PATH: /app/models/vosk-model-en-us-0.22
    volumes:
      - ai_models:/app/models
      - ai_output:/app/output
    networks:
      - smart-classroom-network

  # Media Worker
  media-worker:
    build:
      context: ./media-worker
      dockerfile: Dockerfile
    container_name: smart-classroom-media-worker
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      NODE_ENV: production
      PORT: 5002
      REDIS_URL: redis://redis:6379
      FFMPEG_PATH: /usr/bin/ffmpeg
    depends_on:
      - redis
    volumes:
      - media_uploads:/app/uploads
      - media_output:/app/output
    networks:
      - smart-classroom-network

  # Sheet Sync Service
  sheet-sync:
    build:
      context: ./sheet-sync
      dockerfile: Dockerfile
    container_name: smart-classroom-sheet-sync
    restart: unless-stopped
    ports:
      - "5003:5003"
    environment:
      NODE_ENV: production
      PORT: 5003
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      GOOGLE_REDIRECT_URI: http://localhost:5003/auth/google/callback
    volumes:
      - sheet_storage:/app/storage
      - sheet_credentials:/app/credentials
    networks:
      - smart-classroom-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-classroom-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_AI_SERVICE_URL: http://localhost:5001
      NEXT_PUBLIC_MEDIA_WORKER_URL: http://localhost:5002
      NEXT_PUBLIC_SHEET_SYNC_URL: http://localhost:5003
    depends_on:
      - backend
    networks:
      - smart-classroom-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: smart-classroom-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
      - ai-service
      - media-worker
      - sheet-sync
    networks:
      - smart-classroom-network

volumes:
  mongodb_data:
  redis_data:
  ai_models:
  ai_output:
  media_uploads:
  media_output:
  sheet_storage:
  sheet_credentials:

networks:
  smart-classroom-network:
    driver: bridge
